server:
  error:
    include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: authordetail

logging:
  level:
    root: INFO
    com.grigoryev: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  mongodb:
    embedded:
      version: 5.0.2

---

spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongo

server.port: 8080

#  docker
#---
#
#spring:
#  datasource:
#    url: jdbc:mysql://mysql2/author-db
#    username: user
#    password: pwd
#
#    hikari:
#      initialization-fail-timeout: 60000
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#
#  config:
#    activate:
#      on-profile: docker
#
#  sql:
#    init:
#      platform: mysql
#      mode: always
#
#server.port: 8080
